// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LionPetManagement_HoaLQ.Models;

public partial class LionProfile
{
    public int LionProfileId { get; set; }

    public int LionTypeId { get; set; }

    public string LionName { get; set; }

    public double Weight { get; set; }

    public string Characteristics { get; set; }

    public string Warning { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual LionType LionType { get; set; }
}